/* ============================================================
   convert.js — File/HTML to PDF conversion endpoint
   POST /api/v1/convert
   ============================================================ */

const { authenticate, jsonResponse, errorResponse } = require("./utils/auth");
const { incrementUsage, MAX_BODY_BYTES } = require("./utils/storage");

exports.handler = async (event) => {
  // ── Auth check ──
  const { auth, response } = await authenticate(event, { countUsage: true });
  if (response) return response;

  if (event.httpMethod !== "POST") {
    return errorResponse(405, "Method not allowed. Use POST.");
  }

  // ── Body size check ──
  if (event.body && Buffer.byteLength(event.body, "utf-8") > MAX_BODY_BYTES) {
    return errorResponse(413, "Request body too large. Maximum 10MB.");
  }

  let body;
  try {
    body = JSON.parse(event.body || "{}");
  } catch {
    return errorResponse(400, "Invalid JSON body.");
  }

  const { html, file, format, text, options = {} } = body;

  // ── Validate input ──
  if (!html && !file && !text) {
    return errorResponse(400, "Provide at least one input: 'html', 'file' (base64), or 'text'.", {
      example: {
        html: "<h1>Hello World</h1><p>This is a test PDF.</p>",
        options: { pageSize: "a4", orientation: "portrait" },
      },
    });
  }

  // Determine conversion type
  const conversionType = html ? "html" : text ? "text" : format || "image";

  // Check file size against tier limit
  if (file) {
    const fileSizeBytes = Buffer.from(file, "base64").length;
    const maxBytes = auth.tier.maxFileSizeMB * 1024 * 1024;
    if (fileSizeBytes > maxBytes) {
      return errorResponse(413, `File too large. ${auth.tier.name} plan allows up to ${auth.tier.maxFileSizeMB}MB.`, {
        fileSizeMB: (fileSizeBytes / (1024 * 1024)).toFixed(2),
        limitMB: auth.tier.maxFileSizeMB,
        upgrade: "https://buildpdf.co/api/docs#pricing",
      });
    }
  }

  try {
    // ── Generate PDF ──
    const { jsPDF } = require("jspdf");

    const pageSize = options.pageSize || "a4";
    const orientation = options.orientation || "portrait";
    const margin = options.margin != null ? options.margin : 10;

    const doc = new jsPDF({ orientation, unit: "mm", format: pageSize });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const usableW = pageW - margin * 2;
    const usableH = pageH - margin * 2;

    let pageCount = 1;

    if (conversionType === "html" || html) {
      // ── HTML → PDF (strip tags, render as text for MVP) ──
      const rawHtml = html || Buffer.from(file, "base64").toString("utf-8");
      const plainText = rawHtml.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
      pageCount = renderTextToPdf(doc, plainText, margin, usableW, usableH);

    } else if (conversionType === "text" || text) {
      // ── Text → PDF ──
      const content = text || Buffer.from(file, "base64").toString("utf-8");
      pageCount = renderTextToPdf(doc, content, margin, usableW, usableH);

    } else if (conversionType === "image") {
      // ── Image → PDF ──
      const imgBuffer = Buffer.from(file, "base64");
      const imgFormat = detectImageFormat(imgBuffer);

      if (!imgFormat) {
        return errorResponse(400, "Unsupported image format. Supported: JPG, PNG.");
      }

      const imgData = `data:image/${imgFormat};base64,${file}`;
      doc.addImage(imgData, imgFormat.toUpperCase(), margin, margin, usableW, usableH);
      pageCount = 1;

    } else if (conversionType === "docx") {
      // ── DOCX → PDF (basic text extraction) ──
      // For MVP: extract raw text from docx using basic parsing
      const content = Buffer.from(file, "base64").toString("utf-8");
      pageCount = renderTextToPdf(doc, "[DOCX conversion — full support coming soon]", margin, usableW, usableH);

    } else {
      return errorResponse(400, `Unsupported format: '${conversionType}'. Supported: html, text, image, docx.`);
    }

    // ── Add watermark for free tier ──
    if (auth.tier.watermark) {
      const totalPages = doc.internal.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(160, 160, 160);
        doc.text(
          "Generated by BuildPDF — Free PDF Converter → buildpdf.co",
          pageW / 2,
          pageH - 5,
          { align: "center" }
        );
      }
    }

    // ── Output ──
    const pdfBuffer = Buffer.from(doc.output("arraybuffer"));

    // Increment usage
    await incrementUsage(auth.hash);

    return jsonResponse(200, {
      success: true,
      pdf: pdfBuffer.toString("base64"),
      pages: doc.internal.getNumberOfPages(),
      sizeBytes: pdfBuffer.length,
      watermark: auth.tier.watermark,
      usage: {
        used: auth.quota.used + 1,
        limit: auth.quota.limit,
        remaining: auth.quota.remaining - 1,
      },
      powered_by: "https://buildpdf.co",
    });

  } catch (err) {
    console.error("Conversion error:", err);
    return errorResponse(500, "PDF conversion failed. Please try again.");
  }
};

// ── Text renderer ──
function renderTextToPdf(doc, text, margin, usableW, usableH) {
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);

  const lines = doc.splitTextToSize(text, usableW);
  const lineH = 6;
  const perPage = Math.floor(usableH / lineH);
  let y = margin;
  let linesOnPage = 0;
  let pages = 1;

  for (let i = 0; i < lines.length; i++) {
    if (linesOnPage >= perPage && i > 0) {
      doc.addPage();
      y = margin;
      linesOnPage = 0;
      pages++;
    }
    doc.text(lines[i], margin, y);
    y += lineH;
    linesOnPage++;
  }

  return pages;
}

// ── Image format detection from buffer ──
function detectImageFormat(buffer) {
  if (buffer[0] === 0xff && buffer[1] === 0xd8) return "jpeg";
  if (buffer[0] === 0x89 && buffer[1] === 0x50) return "png";
  return null;
}
